# Generated by Django 2.1.3 on 2018-11-12 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField()),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoolQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creating_tests_app.QuestionBase')),
                ('user_answer', models.BooleanField()),
                ('proper_answer', models.BooleanField()),
            ],
            bases=('creating_tests_app.questionbase',),
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creating_tests_app.QuestionBase')),
            ],
            bases=('creating_tests_app.questionbase',),
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creating_tests_app.QuestionBase')),
                ('user_answer', models.TextField()),
                ('proper_answer', models.TextField()),
            ],
            bases=('creating_tests_app.questionbase',),
        ),
        migrations.CreateModel(
            name='ScaleQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creating_tests_app.QuestionBase')),
                ('user_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), rest_framework.compat.MaxValueValidator(10)])),
                ('proper_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), rest_framework.compat.MaxValueValidator(10)])),
            ],
            bases=('creating_tests_app.questionbase',),
        ),
        migrations.AddField(
            model_name='questionbase',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creating_tests_app.Test'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='creating_tests_app.ChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_proper_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proper_answer', to='creating_tests_app.ChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='creating_tests_app.ChoiceQuestion'),
        ),
    ]
