# Generated by Django 2.1.3 on 2018-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_tests_app', '0001_squashed_0006_auto_20181116_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
