# Generated by Django 2.1.3 on 2018-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbase',
            name='question_type',
            field=models.CharField(choices=[('OP', 'Open question'), ('CO', 'Choice one question'), ('CM', 'Choice multi question'), ('BO', 'Boolean question'), ('SC', 'Scale question')], default='OP', max_length=2),
        ),
    ]
