# Generated by Django 2.1.3 on 2018-11-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creating_tests_app', '0002_questionbase_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='one_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boolquestion',
            name='user_answer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='creating_tests_app.ChoiceQuestion'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='proper_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='user_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questionbase',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='creating_tests_app.Test'),
        ),
    ]
